FROM python:3.10-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    gcc python3-dev libxml2-dev libxslt-dev ffmpeg git \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["python", "app.py"]